# Generated by Django 5.2 on 2025-04-13 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(5)])),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=10)),
                ('stock', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
