# Generated by Django 5.2 on 2025-04-13 02:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.MaxLengthValidator(5), django.core.validators.MinLengthValidator(5)])),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.item', to_field='code')),
                ('header_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sells.sellheader')),
            ],
        ),
    ]
