# Generated by Django 5.2 on 2025-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sells', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellheader',
            name='code',
            field=models.CharField(unique=True),
        ),
    ]
